
bot:
  username: <BOT_USERNAME>
  token: <BOT_TOKEN>

cbr.currency.rates:
  url: <CURRENCY_EXCHANGE_RATES_CBR>

spring:

  datasource:
    username: <POSTGRES_USER>
    password: <POSTGRES_PASSWORD>
    url: jdbc:postgresql://<DB_SOCKET>/<POSTGRES_DB>
    properties:
      schema: <SCHEMA_ASSISTANT_BOT>

  flyway:
    enabled: true
    create-schemas: true
    schemas: <SCHEMA_ASSISTANT_BOT>
    url: jdbc:postgresql://<DB_SOCKET>/<POSTGRES_DB>
    user: <POSTGRES_USER>
    password: <POSTGRES_PASSWORD>
    locations : classpath:db/migration

  jpa:
    properties:
      hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate:
      format_sql: true
  sql:
    init.mode: always
