CREATE SCHEMA IF NOT EXISTS assistant_bot;

CREATE TABLE IF NOT EXISTS assistant_bot.users (
  id                            BIGINT         NOT NULL PRIMARY KEY,
  first_name                    VARCHAR(128)   NOT NULL,
  last_name                     VARCHAR(128),
  username                      VARCHAR(128),
  is_bot                        BOOLEAN        NOT NULL,
  language_code                 VARCHAR(12),
  can_join_groups               BOOLEAN,
  can_read_all_group_messages   BOOLEAN,
  supports_inline_queries       BOOLEAN,
  is_premium                    BOOLEAN,
  added_to_attachment_menu      BOOLEAN
);

CREATE TABLE IF NOT EXISTS assistant_bot.assistant_bot_history (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  text_message  VARCHAR(4096),
  chat_id       BIGINT      NOT NULL,
  user_id       BIGINT      REFERENCES assistant_bot.users(id) ON DELETE CASCADE,
  created_at    TIMESTAMP   DEFAULT now() NOT NULL
);

